### ISSUE TITLE
Parsing label mapping from VITON to ACGPN

### ISSUE THREAD

**Issue by minar09** [switchablenorms/DeepFashion_Try_On#15]
Hello, thank you very much for your great work! The pipeline is deeply thought and designed smartly. It would be really great to know the full label mapping between original VITON label maps and your generated new maps. Also, segmentation map you provided in the README has some number gaps. Can you please tell me what's the reason? Thank you.

**Comment by ChongjianGE** [comment]
Hi @minar09 
There are 20 labels in total. Here is a reference repo about the total parsing labels. [Self-Correction-Human-Parsing](https://github.com/PeikeLi/Self-Correction-Human-Parsing) However, we only use the most common 11 labels for VITON dataset.  
Actually, different numbers are assigned to different parts of humans. The reconstructed0 parsing labels are presented in the README.  Thus, the order of label numbers is quite different from [Self-Correction-Human-Parsing](https://github.com/PeikeLi/Self-Correction-Human-Parsing).

**Comment by minar09** [comment]
Hi @ChongjianGE , thank you so much for the answer. I think I understand why you used different labels, since VITON dataset does not have images including coat, scarf, glove etc. However, I think VITON dataset has some skirt images which could be included in your ACGPN, but maybe that's okay regarding the try-on cloth is only for upper-body. Thank you.

**Comment by Learningchen** [comment]
what's label 7 Noise?

**Comment by ChongjianGE** [comment]
Hi @Learningchen,
You can ignore the label 7. It does no harm to try-on performance.

**Comment by josearangos** [comment]
First I want to tell you that I am very surprised by the excellent results in the inference, thank you very much for contributing with this architecture, I admire you very much.

After making inferences with custom images I get an unexpected result with some images as shown below:
Couldn't this be because you don't have the nose tag?


![image](https://user-images.githubusercontent.com/13352055/95607785-db0a0e80-0a21-11eb-96d6-47f730cda2c7.png)
![image](https://user-images.githubusercontent.com/13352055/95607798-de04ff00-0a21-11eb-927c-07d8fca00da2.png)
![image](https://user-images.githubusercontent.com/13352055/95607812-e1988600-0a21-11eb-93c4-f60169ce08a4.png)
![image](https://user-images.githubusercontent.com/13352055/95607828-e65d3a00-0a21-11eb-87f1-b1f36e8112a7.png)

**Comment by AjayMudhai** [comment]
@josearangos Hi, were u able to figure out the reason for problem in nose generation? Kindly let us know.
