### ISSUE TITLE
how to inference model use other image?

### ISSUE THREAD

**Issue by kelisiya** [switchablenorms/DeepFashion_Try_On#4]
There is a inference model , but I don't the input:label, label_ref, image_ref；Can you tell me what they mean? Because inference should only need to input model pictures and clothes to successfully predict, but there are 11 parameters in train model .

**Comment by HAN-YANG-HIT** [comment]
you can just run `python test.py`

**Comment by nothingwqy** [comment]
running python test.py will start the training process instead of inference. Can you update it?

**Comment by HAN-YANG-HIT** [comment]
it is actually test

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Qingyun Wang <notifications@github.com>
发送时间: Tuesday, June 2, 2020 10:38:06 PM
收件人: switchablenorms/DeepFashion_Try_On <DeepFashion_Try_On@noreply.github.com>
抄送: Yang; Han <yanghanhuoying@live.com>; Comment <comment@noreply.github.com>
主题: Re: [switchablenorms/DeepFashion_Try_On] how to inference model use other image? (#4)


running python test.py will start the training process instead of inference. Can you update it?

―

**Comment by nothingwqy** [comment]
Thanks for clarifying, I think I understand the code now! The generated image will store in the 'sample' folder. Would you share some more information on data-preprocessing? I image that the labels are obtained from some segmentation model, the pose are obtained from openpose, is that right? What is the 'edge' variable?

**Comment by HAN-YANG-HIT** [comment]
We will release train code next week, and also rearrange the test code for easy access.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Qingyun Wang <notifications@github.com>
发送时间: Wednesday, June 3, 2020 12:29:06 AM
收件人: switchablenorms/DeepFashion_Try_On <DeepFashion_Try_On@noreply.github.com>
抄送: Yang; Han <yanghanhuoying@live.com>; Comment <comment@noreply.github.com>
主题: Re: [switchablenorms/DeepFashion_Try_On] how to inference model use other image? (#4)


Thanks for clarifying, I think I understand the code now! The generated image will store in the 'sample' folder. Would you share some more information on data-preprocessing? I image that the labels are obtained from some segmentation model, the pose are obtained from openpose, is that right? What is the 'edge' variable?

―

**Comment by kelisiya** [comment]
Thanks for your work

**Comment by snarb** [comment]
@HAN-YANG-HIT  directory structure do we need to make it works?
